package org.demo.core.mybatis.mapper;

import org.demo.core.mybatis.model.Permission;

import java.util.Set;

public interface PermissionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    Permission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKey(Permission record);

    /**
     * 查询权限代码
     * @param userid
     * @return
     */
    Set<Permission> queryCodeByUserid(Integer userid);
}