package org.demo.core.mybatis.mapper;

import org.demo.core.mybatis.model.Role;

import java.util.Set;

public interface RoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role
     *
     * @mbg.generated Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKey(Role record);
}