package org.demo.core.mybatis.mapper;

import org.demo.core.mybatis.model.RolePermission;

public interface RolePermissionMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    RolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table role_permission
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKey(RolePermission record);
}