package org.demo.core.mybatis.mapper;

import org.demo.core.mybatis.model.UserRole;

public interface UserRoleMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_role
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKey(UserRole record);
}