package org.demo.core.mybatis.mapper;

import org.demo.core.mybatis.model.User;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    int updateByPrimaryKey(User record);
}