package org.demo.core.mybatis.model;

public class Permission {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column permission.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
     * @return  the value of permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
     * @param id  the value for permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
     * @return  the value of permission.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
     * @param name  the value for permission.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column permission.code
     * @return  the value of permission.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column permission.code
     * @param code  the value for permission.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }
}