package org.demo.core.mybatis.model;

public class Role {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
     * @return  the value of role.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
     * @param id  the value for role.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.name
     * @return  the value of role.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.name
     * @param name  the value for role.name
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.code
     * @return  the value of role.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.code
     * @param code  the value for role.code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }
}