package org.demo.core.mybatis.model;

public class RolePermission {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.p_id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer p_id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.r_code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String r_code;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.id
     * @return  the value of role_permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.id
     * @param id  the value for role_permission.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.p_id
     * @return  the value of role_permission.p_id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.p_id
     * @param p_id  the value for role_permission.p_id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.r_code
     * @return  the value of role_permission.r_code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getR_code() {
        return r_code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.r_code
     * @param r_code  the value for role_permission.r_code
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setR_code(String r_code) {
        this.r_code = r_code;
    }
}