package org.demo.core.mybatis.model;

import java.util.Date;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickname
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String nickname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String gender;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Integer age;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Date create_time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.last_online_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private Date last_online_time;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickname
     * @return  the value of user.nickname
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickname
     * @param nickname  the value for user.nickname
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
     * @return  the value of user.username
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
     * @param username  the value for user.username
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
     * @return  the value of user.password
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
     * @param password  the value for user.password
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
     * @return  the value of user.gender
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
     * @param gender  the value for user.gender
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
     * @return  the value of user.age
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
     * @param age  the value for user.age
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
     * @return  the value of user.phone
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
     * @param phone  the value for user.phone
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
     * @return  the value of user.create_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
     * @param create_time  the value for user.create_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.last_online_time
     * @return  the value of user.last_online_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public Date getLast_online_time() {
        return last_online_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.last_online_time
     * @param last_online_time  the value for user.last_online_time
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setLast_online_time(Date last_online_time) {
        this.last_online_time = last_online_time;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
     * @return  the value of user.status
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
     * @param status  the value for user.status
     * @mbg.generated  Wed Feb 15 15:36:42 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }
}